spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB
server.port=9000

logging.level.root=INFO

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=theta-bulk-upload-group
spring.kafka.consumer.auto-offset-reset=earliest
app.kafka.topic.upload-jobs=theta.upload.jobs
app.kafka.topic.upload-results=theta.upload.results